curl response code of 000 should not cause the script to exit

diff --git a/jobs/kibana/templates/bin/post-start.erb b/jobs/kibana/templates/bin/post-start.erb
--- a/jobs/kibana/templates/bin/post-start.erb
+++ b/jobs/kibana/templates/bin/post-start.erb
@@ -6,7 +6,11 @@ echo "Waiting <%= p("kibana.health.timeout") %>s for kibana to accept connection
 elapsed=0
 until [ $elapsed -ge <%= p("kibana.health.timeout") %> ]
 do
+  # We have to set and unset the 'e' flag around the curl as a return code of 000 (no network) will result in an error.
+  # This return code is valid and therefore we want to ignore this as an error.
+  set +e
   CODE=`curl -s -o /dev/null -w "%{http_code}" http://<%= p("kibana.host") %>:<%= p("kibana.port") %>`
+  set -e
   if [[ "$CODE" == "302" ]]; then
     echo Done!
     break
