Parameterize kibana health check. (#78)

diff --git a/jobs/kibana/templates/bin/post-start.erb b/jobs/kibana/templates/bin/post-start.erb
--- a/jobs/kibana/templates/bin/post-start.erb
+++ b/jobs/kibana/templates/bin/post-start.erb
@@ -4,19 +4,18 @@ set -e
 
 <% if !p("kibana.health.disable_post_start") %>
 
-echo "Waiting 2m for kibana to accept connections..."
-n=0
-until [ $n -ge 24 ]
+echo "Waiting <%= p("kibana.health.timeout") %>s for kibana to accept connections..."
+elapsed=0
+until [ $elapsed -ge <%= p("kibana.health.timeout") %> ]
 do
   curl -is http://<%= p("kibana.host") %>:<%= p("kibana.port") %> 2>&1 && break
-  n=$[$n+1]
-  echo "Waiting for kibana to accept connections ($n of 24)..."
-  sleep 5
+  elapsed=$[$elapsed+<%= p("kibana.health.interval") %>]
+  sleep <%= p("kibana.health.interval") %>
 done
 
-if [ "$n" -ge "24" ]; then
-   echo "ERROR: Cannot connect to kibana. Exiting..."
-   exit 1
+if [ "$elapsed" -ge "<%= p("kibana.health.timeout") %>" ]; then
+  echo "ERROR: Cannot connect to kibana. Exiting..."
+  exit 1
 fi
 
 <% end %>
